name: 🔒 Security Vulnerability Report
description: Report a security vulnerability in this project
title: "[SECURITY] "
labels: ["security", "needs-triage", "vulnerability"]
assignees:
  - markcoleman

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Please do not report security vulnerabilities in public issues!**

        If this is a security vulnerability, please email us privately instead of creating a public issue.
        For non-security bugs, please use the regular bug report template.

  - type: checkboxes
    id: confirm-security
    attributes:
      label: Security Confirmation
      description: Please confirm this is NOT a security vulnerability before proceeding
      options:
        - label: This is NOT a security vulnerability (it's safe to report publicly)
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - Minimal security impact
        - Medium - Moderate security impact
        - High - Significant security impact
        - Critical - Severe security impact
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Dependency Vulnerability
        - Code Vulnerability (XSS, Injection, etc.)
        - Authentication/Authorization
        - Data Exposure
        - Salesforce Security (CRUD/FLS, SOQL Injection)
        - Configuration Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue
      placeholder: Provide a clear description of the security issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this security issue?
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: What is the potential impact of this vulnerability?
      placeholder: Describe the potential security impact...
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this issue?
      placeholder: Any suggestions for mitigating or fixing this vulnerability...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details where this was discovered
      placeholder: |
        - Salesforce org type: (Developer/Sandbox/Production)
        - Browser: 
        - Node.js version:
        - Any other relevant environment details
    validations:
      required: true
