---
name: Dependency Review

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail the action if any vulnerabilities are found
          fail-on-severity: moderate
          # Deny specific licenses that may be problematic
          deny-licenses: GPL-2.0, GPL-3.0, LGPL-2.1, LGPL-3.0
          # Enable vulnerability check
          vulnerability-check: true
          # Generate summary comment on PR
          comment-summary-in-pr: always

      - name: Upload dependency review results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-review-results
          path: dependency-review-results.json
          retention-days: 30
