---
name: Salesforce CI

"on":
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  salesforce-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf version

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SALESFORCE_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SALESFORCE_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SALESFORCE_USERNAME }} \
            --instance-url ${{ secrets.SALESFORCE_INSTANCE_URL || 'https://login.salesforce.com' }} \
            --alias DevHub
        env:
          SALESFORCE_JWT_KEY: ${{ secrets.SALESFORCE_JWT_KEY }}
          SALESFORCE_CLIENT_ID: ${{ secrets.SALESFORCE_CLIENT_ID }}
          SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}

      - name: Create scratch org
        run: |
          sf org create scratch \
            --definition-file config/project-scratch-def.json \
            --alias scratch-org \
            --duration-days 1 \
            --target-dev-hub DevHub

      - name: Deploy source to scratch org
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org scratch-org

      - name: Run Apex tests
        run: |
          sf apex run test \
            --target-org scratch-org \
            --wait 10 \
            --result-format human \
            --code-coverage

      - name: Clean up
        if: always()
        run: |
          sf org delete scratch --target-org scratch-org --no-prompt || true
          rm -f server.key
