---
name: Security Vulnerability Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run daily at 2 AM UTC for continuous monitoring
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  vulnerability-scan:
    name: Vulnerability Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit (High severity)
        run: |
          echo "## NPM Security Audit Results" > security-report.md
          npm audit --audit-level=high --json > npm-audit.json || true
          if [ -s npm-audit.json ]; then
            echo "⚠️ High severity vulnerabilities found!" >> security-report.md
            echo "```json" >> security-report.md
            cat npm-audit.json >> security-report.md
            echo "```" >> security-report.md
          else
            echo "✅ No high severity vulnerabilities found." >> security-report.md
          fi

      - name: Run npm audit (All levels)
        run: |
          echo "" >> security-report.md
          echo "## Complete Audit Report" >> security-report.md
          npm audit --json > npm-audit-complete.json || true
          if [ -s npm-audit-complete.json ]; then
            echo "Full audit results available in artifacts." >> security-report.md
          fi
        continue-on-error: true

      - name: Check for malicious packages
        run: |
          echo "" >> security-report.md
          echo "## Package Security Check" >> security-report.md
          # Basic check for suspicious package names or versions
          npm list --depth=0 --json > package-list.json
          if grep -i "bitcoin\|crypto\|mining\|hack" package-list.json; then
            echo "⚠️ Potentially suspicious packages detected!" >> security-report.md
          else
            echo "✅ No suspicious packages detected." >> security-report.md
          fi

      - name: License compliance check
        run: |
          echo "" >> security-report.md
          echo "## License Compliance" >> security-report.md
          # Check for GPL or other restrictive licenses
          npm ls --json > license-check.json || true
          if grep -i "GPL\|AGPL\|LGPL" license-check.json; then
            echo "⚠️ Potentially restrictive licenses found!" >> security-report.md
          else
            echo "✅ License compliance check passed." >> security-report.md
          fi

      - name: Generate security summary
        run: |
          echo "" >> security-report.md
          echo "## Summary" >> security-report.md
          echo "- Scan Date: $(date)" >> security-report.md
          echo "- Node.js Version: $(node --version)" >> security-report.md
          echo "- NPM Version: $(npm --version)" >> security-report.md
          echo "- Total Dependencies: $(npm list --depth=0 2>/dev/null | grep -c "├──\|└──" || echo "0")" >> security-report.md
          cat security-report.md

      - name: Upload security artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-scan-results
          path: |
            security-report.md
            npm-audit.json
            npm-audit-complete.json
            package-list.json
            license-check.json
          retention-days: 30

      - name: Fail on high severity vulnerabilities
        run: |
          if [ -s npm-audit.json ] && grep -q '"severity":"high"\|"severity":"critical"' npm-audit.json; then
            echo "❌ High or critical severity vulnerabilities found!"
            exit 1
          fi
